/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KXsgI3U1vsI
 */
import { UserArticle } from "@/features/article/types/UserArticle"
import { UserArticleListItem } from "../../UserArticleListItem/user-article-list-item"

export type UserArticleListViewProps = {
  userArticles: UserArticle[]
}

export function UserArticleListView({ userArticles }: UserArticleListViewProps) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="container py-4 md:py-6">
        <h1 className="text-2xl font-bold tracking-tighter">My Articles</h1>
      </div>
      <main className="flex-1 py-4 md:py-6">
        <div className="container grid max-w-6xl gap-4 px-4 md:px-6">
          {userArticles.length === 0 && (
            <p>No articles found.</p>
          )}
          {userArticles.map((article) => (
            <UserArticleListItem key={article.id} userArticle={article} />
          ))}
        </div>
      </main>
    </div>
  )
}
