/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KXsgI3U1vsI
 */
import { UserArticle } from "@/features/article/types/UserArticle"
import { UserArticleListView } from "./view/user-article-list-view"

export function UserArticleList() {
  // TODO: ここで記事一覧を取得する
  // 今はモック
  const mockUserArticles: UserArticle[] = [
    {
      id: "1",
      title: "Introducing Shadcn UI",
      publishedAt: "August 23, 2023",
      description: "Shadcn UI is a delightful design system for creating beautiful websites and web apps.",
    },
    {
      id: "2",
      title: "Building Accessible Web Components",
      publishedAt: "June 10, 2023",
      description: "Learn how to create web components with accessibility in mind.",
    },
    {
      id: "3",
      title: "Mastering Tailwind CSS with Shadcn",
      publishedAt: "April 5, 2023",
      description: "Discover the power of utility-first CSS and the elegance of Shadcn components.",
    },
  ]

  return (
    <UserArticleListView userArticles={mockUserArticles} />
  )
}
